# Generated by Django 4.2.7 on 2024-04-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_pessoa_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
